// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TerraxLighting","status":true,"description":"v1.5.1 Creates an extra layer that darkens a map and adds lightsources!","parameters":{"Player radius":"700","Add to options":"Yes","Option menu entry":"Lighting effects","Reset Lights":"No","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Flashlight offset":"0","Screensize X":"1200","Screensize Y":"720","Kill Switch":"No"}},
{"name":"ScreenChanger","status":true,"description":"v1.1 Изменение разрешения через скриптовый вызов в ивенте.","parameters":{"Screen Width":"1200","Screen Height":"720"}},
{"name":"OuterSelfSwitch","status":true,"description":"Внешнее переключение самост.операторов (self switch) для событий","parameters":{}},
{"name":"YEP_MessageCore","status":true,"description":"Adds more features to the Message Window to customized the\nway your messages appear and functions.","parameters":{"---General---":"","Default Rows":"4","Default Width":"Graphics.boxWidth","Face Indent":"Window_Base._faceWidth + 24","Fast Forward":"Input.isPressed('pagedown')","Word Wrapping":"false","---Font---":"","Font Name":"GameFont","Font Size":"28","Font Size Change":"12","Font Changed Max":"96","Font Changed Min":"12","---Name Box---":"","Name Box Buffer X":"-28","Name Box Buffer Y":"0","Name Box Padding":"this.standardPadding() * 4","Name Box Color":"0","Name Box Clear":"false","Name Box Added Text":"\\c[6]"}},
{"name":"Event Distance Sensor","status":true,"description":"v1.0 Event Sensor. Действия событий, основанные от расстояния от игрока.","parameters":{}},
{"name":"Alpha_ABS","status":true,"description":"ABS \"Alpha\"","parameters":{"Enemy Dead Switch":"D","After Dead Map":"0","Cast Animation":"0","Level Up Animation":"49","Revive Animation":"45","Use default cast SE":"true","Auto loot enemies":"false","UI visibility control":"true","UI position control":"true","Force English":"false"}}
];
